ENG-4704 adds apiKey to hub registry
entando-k8s/entando-component-manager pull request #296
Opened 2023-03-21 17:17 UTC by antromeo

2023-03-22 14:21 UTC, antromeo commented on src/main/java/org/entando/kubernetes/model/entandohub/EntandoHubRegistry.java
>      @Schema(accessMode = Schema.AccessMode.WRITE_ONLY)
it seems that JsonProperty has some issues with Schema AccessMode annotation. I found these conversations about it.
https://github.com/springdoc/springdoc-openapi/issues/902
https://github.com/springdoc/springdoc-openapi/issues/994

the root cause appears to be swagger-core:
https://github.com/swagger-api/swagger-core/issues/3905

2023-03-28 08:59 UTC, firegloves requested changes

2023-03-28 08:59 UTC, firegloves commented on src/main/java/org/entando/kubernetes/model/entandohub/EntandoHubRegistry.java
>      @Schema(accessMode = Schema.AccessMode.WRITE_ONLY)
@JsonIgnore is not suitable for your needs?

2023-03-28 14:32 UTC, firegloves approved these changes
LGTM

2023-03-30 09:42 UTC, merged