ENG-4983 Amend the ComponentManager endpoint for delete POST /components/{bundleCode}/uninstall
entando-k8s/entando-component-manager pull request #322
Opened 2023-06-20 16:18 UTC by entgigi

2023-06-22 08:05 UTC, mirkoPan commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
> +    private EntandoCoreComponentDeleteRequest convertEntityToDto(EntandoBundleComponentJobEntity entity) {
Consider putting this method in the dto in order to have greater uniformity in the mapping process than solutions adopted elsewhere in the code. On the other hand, the coupling of this suggestion, which would bind the entity with the dto, must be considered,

2023-06-22 08:05 UTC, mirkoPan commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
> +                String uninstallErrors = om.writeValueAsString(response.getComponents().stream()
consider using a more descriptive variable

2023-06-22 12:19 UTC, entgigi commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
> +                String uninstallErrors = om.writeValueAsString(response.getComponents().stream()
done, pls resolve if it's ok for you

2023-06-22 12:19 UTC, entgigi commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
> +    private EntandoCoreComponentDeleteRequest convertEntityToDto(EntandoBundleComponentJobEntity entity) {
done, pls resolve if it's ok for you

2023-06-26 09:35 UTC, mirkoPan approved these changes
LGTM

2023-07-05 15:24 UTC, firegloves requested changes

2023-07-05 15:24 UTC, firegloves commented on src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
> +            var usage = (ResponseEntity<SimpleRestResponse<EntandoCoreComponentDeleteResponse>>) retryer.execute(r);
Are we deleting data or fetching usage details? Why is the var called `usage`?

2023-07-05 15:24 UTC, firegloves commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
> +                JobProgress uninstallProgress = new JobProgress(1.0 / (uninstallJobs.size() + 1));
Please add a comment to explain why we need the new `+ 1`

2023-07-05 15:24 UTC, firegloves commented on src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
> +        //WireMock.setGlobalRandomDelay(delayDistribution);
please delete this commented line

2023-07-05 15:24 UTC, firegloves commented on src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
> +        */
please delete these commented lines

2023-07-06 08:31 UTC, entgigi commented on src/main/java/org/entando/kubernetes/client/core/DefaultEntandoCoreClient.java
> +            var usage = (ResponseEntity<SimpleRestResponse<EntandoCoreComponentDeleteResponse>>) retryer.execute(r);
done

2023-07-06 08:33 UTC, entgigi commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleUninstallService.java
> +                JobProgress uninstallProgress = new JobProgress(1.0 / (uninstallJobs.size() + 1));
done

2023-07-06 08:35 UTC, entgigi commented on src/test/java/org/entando/kubernetes/utils/TestInstallUtils.java
> +        //WireMock.setGlobalRandomDelay(delayDistribution);
done

2023-07-06 08:36 UTC, entgigi commented on src/test/java/org/entando/kubernetes/controller/mockmvc/InstallFlowTest.java
> +        */
done

2023-07-06 08:43 UTC, firegloves approved these changes
LGTM

2023-07-27 10:58 UTC, merged