ENG-5059 multiple idps
entando-k8s/entando-component-manager pull request #353
Opened 2023-08-09 15:28 UTC by firegloves

2023-08-11 10:02 UTC, entgigi requested changes

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/security/MultipleIdps.java
> +    private String composeIssuerUri(TenantConfigDTO tenantConfig) {
@firegloves  we should discuss my changes to this method KcRealm cannot be blank, shout validate it for all tenants (primary too)

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantConfiguration.java
> +//@Profile("!test  & !testdb")
@firegloves we should discuss this, i removed test configuration

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantConfiguration.java
> +            @Value("${entando.app.host.name:localhost}") final String primaryHostName,
@firegloves we should discuss this, it could be dangerous, the app hostname for primary should be added by default to componentManager by operator

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantConfiguration.java
> +    public static class PrimaryTenantConfig extends TenantConfigDTO {
IMHO I think it's better to add a builder or setter directly to DTO, this class is never used, you were forced to duplicate the DTO only because it misses the needed method, can we discuss it ?

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantFilter.java
> +        return tenantConfigs.stream().filter(t -> getFqdnTenantNames(t).contains(search)).findFirst()
`contains` function uses equals, are we sure we shouldn't use equalsIgnoreCase ?

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantFilter.java
> +
@firegloves about the problems you talked to me did you read this https://docs.spring.io/spring-boot/docs/2.5.15/reference/htmlsingle/#howto.webserver.use-behind-a-proxy-server ?

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantFilter.java
> +    private static final String REQUEST_SERVER_NAME = "Request server name";
IMHO I think we could use the following constants without redefining it:
```
com.google.common.net.HttpHeaders.X_FORWARDED_HOST;
com.google.common.net.HttpHeaders.HOST
```

2023-08-11 10:02 UTC, entgigi commented on src/test/java/org/entando/kubernetes/config/security/AuthenticationManagerConfigTest.java
> +//package org.entando.kubernetes.config.security;
After the last changes to test I think we could remove this file @firegloves do you agree ?

2023-08-11 10:02 UTC, entgigi commented on src/main/java/org/entando/kubernetes/config/tenant/TenantFilter.java
> +    public String fetchTenantCode(final String headerXForwardedHost,
why is this method public? I think the reason could be to test, the we should remove this logic from the filter and put it inside a utility class.

2023-08-11 10:02 UTC, entgigi commented on src/test/java/org/entando/kubernetes/config/tenant/TenantFilterTest.java
> +        String tenantCode = filter2.fetchTenantCode("tenant2.entando.com", "", "");
you should add a test to be sure that  a second-level domain will not match with a third-level one

2023-08-11 10:02 UTC, entgigi commented on src/test/java/org/entando/kubernetes/utils/EntandoKeycloakMockServer.java
> +    public static void addKeycloakOidcEndpoints(WireMockServer wireMockServer, int port, String realm) {
@firegloves we need to discuss it

2023-08-11 10:02 UTC, entgigi commented on src/test/java/org/entando/kubernetes/utils/TenantContextJunitExt.java
> +    @Override
@firegloves I added a clean after all, this was useful to find tests that need to use this junit extension, what do you think?

2023-08-11 10:02 UTC, entgigi commented on src/test/java/org/entando/kubernetes/utils/TenantSecurityKeycloakMockServerJunitExt.java
> +        wireMockServer = EntandoKeycloakMockServer.mockAndStartServer(8899, "entando");
to discuss with @firegloves

2023-08-28 10:22 UTC, entgigi approved these changes
LGTM

2023-08-28 10:22 UTC, mirkoPan approved these changes
LGTM

2023-08-28 10:24 UTC, merged