ENG-4273: uninstalls orphaned components during installation
entando-k8s/entando-component-manager pull request #374
Opened 2023-09-11 08:28 UTC by antromeo

2023-09-19 13:49 UTC, antromeo commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
> +                        .filter(i -> {
@firegloves note that resources in file browser are preserved

2023-10-06 13:36 UTC, firegloves requested changes

2023-10-06 13:36 UTC, firegloves commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
> +                    return true;
Please consider extracting this function to a method with a comprehensive name just to ease the reading process

2023-10-06 13:36 UTC, firegloves commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
> +                    return false;
Please consider extracting this function to a method with a comprehensive name just to ease the reading process. Might it also be worth adding a sort of `isTypeAppBuilder` within the WidgetDescriptor itself?

2023-10-06 13:36 UTC, firegloves commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
> +                    return cj;
This code should be already present in the same file, please centralize it to a designated method.

2023-10-06 13:36 UTC, firegloves commented on src/main/java/org/entando/kubernetes/service/digitalexchange/job/EntandoBundleInstallService.java
> +    // TODO: moves the inner class
can we delete this TODO?

2023-10-09 13:55 UTC, firegloves approved these changes
LGTM

2023-11-30 09:35 UTC, merged