ENG-5083 Handle database migration on update
entando-k8s/entando-component-manager pull request #391
Opened 2023-11-15 12:44 UTC by MEM2677

When the CM gets updated by the operator (e.g. due to an Entando update), the CM must be able to apply liquibase changelogs to every tenant instance.

2023-11-16 16:11 UTC, firegloves requested changes

2023-11-16 16:11 UTC, firegloves commented on Dockerfile
> +#COPY target/generated-resources/licenses /licenses
Please uncomment this line

2023-11-16 16:11 UTC, firegloves commented on src/main/java/org/entando/kubernetes/config/tenant/TenantDataSourceConfiguration.java
> +                log.debug("Moving Liquibase resources from JAR to {}", destinationFile.toFile().getAbsolutePath());
"Moving" implies the action has still to be made. Could we change it to "Moved" or better do we want to move this line up?

2023-11-16 16:12 UTC, firegloves commented on src/main/java/org/entando/kubernetes/config/tenant/TenantDataSourceConfiguration.java
> +                log.debug("Moving Liquibase resources from JAR to {}", destinationFile.toFile().getAbsolutePath());
I think it's better moving the line up, so that the log appears also when the real operation produces an error

2023-11-23 13:01 UTC, MEM2677 commented on Dockerfile
> +#COPY target/generated-resources/licenses /licenses
Done!

2023-11-23 13:01 UTC, MEM2677 commented on src/main/java/org/entando/kubernetes/config/tenant/TenantDataSourceConfiguration.java
> +                log.debug("Moving Liquibase resources from JAR to {}", destinationFile.toFile().getAbsolutePath());
Done!

2023-11-23 13:25 UTC, firegloves approved these changes
LGTM

2023-12-05 15:22 UTC, merged